### ISSUE TITLE
You are checking the same attribute.

### ISSUE THREAD

**Issue by castelloms** [JanssenProject/jans-auth-server#117]
https://github.com/JanssenProject/jans-auth-server/blob/1120d7b021cc0a5dab2a64e5cf67a3a7b32da56d/model/src/main/java/io/jans/as/model/util/CertUtils.java#L126

**Comment by yuriyz** [comment]
Thank you for catching this typo. Fixed https://github.com/JanssenProject/jans-auth-server/commit/305507f9fddd6600fdbddb1c036f966cc49de7d8
