### ISSUE TITLE
Scopes: Add configuration option to specify "Private"

### ISSUE THREAD

**Issue by nynymike** [JanssenProject/jans-auth-server#144]
Customers may want to supress publication of certain scopes in the configuration endpoint. An easy fix would be to add a Scope entity property for `scopePrivate` : `enabled` | `disabled`, which would supress publication of the scope in the OpenID configuration endpoint.

**Comment by yuriyz** [comment]
Actually we already have `showInConfigurationEndpoint` scope attribute which controls whether to show scope on discovery endpoint or not. Closing this ticket. Please re-open it in case we need rename property.

@ossdhaval would you please check we have it described in janssen docs ?
