### ISSUE TITLE
Dynamic Client Registration - support JWT as payload for POST/PUT operations

### ISSUE THREAD

**Issue by nynymike** [JanssenProject/jans-auth-server#22]
FAPI : Dynamic registration - support JWS as payload for POST/PUT operations

Need to support headers:
* `content-type` : `application/jwt`
* `accept`:`application/json`
* `accept-encoding`:`gzip, deflate, br`

Basically, there are two JWTs: the DCR payload itself, and the software statement. Both of the signatures need to be verified for these JWTs. 

[RFC-7591](https://tools.ietf.org/html/rfc7591#section-3.1) defines `software_statement` as the JSON claim. So we can reliable get it from there in the DCR payload.

The cryptographic key to verify the DCR payload JWT should be obtained either from a JWKS_URI contained in the software statement itself, or from a auth-server JSON property. For example, in the software statement may have a claim `softaware_jwks_endpoint`. So two properties are needed: `dcrPayloadSignatureValidationJwksURI` or `dcrSignatureValidationSoftwareStatementJwksClaimURI`. If both are specified, the jwks_uri specified in the software statement should take precedence.

To verify the software_statement JWT, we need a JSON property `dcrSoftwareStatementJwksEndpoint`. 

We should also have a JSON property to toggle verification: `dcrSoftwareStatementSignatureValidationEnabled` and `dcrPayloadSignatureValidationEnabled`

If either of the software statement signature validations fail, it's important to return an informative message about which JWT validation failed to what jwks endpoint. 

See also:
* https://openbanking.atlassian.net/wiki/spaces/DZ/pages/1078034771/Dynamic+Client+Registration+-+v3.2#DynamicClientRegistration-v3.2-POST/register
* Openbanking swagger https://github.com/OpenBankingUK/directory-api-specs/blob/master/directory-api-swagger.yaml

**Comment by nynymike** [comment]
Moved to https://github.com/JanssenProject/jans-auth-server/issues/22

**Comment by nynymike** [comment]
I just noticed there are already some JSON properties for software statement handling

file:///var/folders/fn/zxvdjs797k34sqw7bt7_mtf00000gn/T/TemporaryItems/NSIRD_screencaptureui_Ut6ssm/Screen%20Shot%202021-02-11%20at%201.51.45%20PM.png

**Comment by yuriyz** [comment]
Following configuration properties are going to be added for DCR validation.

- `dcrSignatureValidationEnabled` - enabled DCR signature validation
- `dcrSignatureValidationSoftwareStatementJwksURIClaim` - specified claim name inside software statement. Value of claim should point to JWKS URI.
- `dcrSignatureValidationSoftwareStatementJwksClaim` - specified claim name inside software statement. Value of claim should point to inlined JWKS.
- `dcrSignatureValidationJwksUri` - specifies JWKS URI for all DCR's validations.
- `dcrSignatureValidationJwks - specifies JWKS for all DCR's validations.

Re: software statement validation, yes, correct. We already have `softwareStatementValidationType` and `softwareStatementValidationClaimName` (for JWKS and JWKS_URI values).

`softwareStatementValidationType` - values are.
- NONE - validation is skipped for software statement
- SCRIPT - (default), invokes `getSoftwareStatementJwks` of dynamic registration script which has to return jwks.
- JWKS - claim name within software statement that has inlined JWKS
- JWKS_URI - claim name within software statement that points to JWKS URI that should lead to keys.

**Comment by yuriyz** [comment]
Implemented : both server side and client side.

Client Test 
https://github.com/JanssenProject/jans-auth-server/blob/029fa2462e5259019bf7597c040ec90dc7abb81d/client/src/test/java/io/jans/as/client/ws/rs/RegistrationWithSoftwareStatement.java#L477

@shmorri would you please update Jans docs according to this comment ?

https://github.com/JanssenProject/jans-auth-server/issues/22#issuecomment-779150822

**Comment by pujavs** [comment]
Verified DCR changes for jans-config-api as well as jans-cli. Changes working fine. 
Only change done and checked in are swagger spec changes.
Evidence:
[Issue#22.xlsx](https://github.com/JanssenProject/jans-auth-server/files/6069401/Issue.22.xlsx)
