### ISSUE TITLE
Currently LDAP and CB builds work but spanner and SQL does not.

### ISSUE THREAD

**Issue by yuriyz** [JanssenProject/jans-auth-server#316]
**Describe the bug**
Currently LDAP and CB builds work but spanner and SQL does not. Most probably it's something missed in schema here:

https://github.com/JanssenProject/jans-setup/blob/fabe99f8e7027ccfe7fa01ab25c163160571d172/static/rdbm/mysql_index.json

https://github.com/JanssenProject/jans-setup/blob/fabe99f8e7027ccfe7fa01ab25c163160571d172/static/rdbm/spanner_index.json

We have to correct it to get all builds successful.

**Comment by yurem** [comment]
DB which has static schema complains about column "dpop". Sample exception:
```
Caused by: com.google.cloud.spanner.SpannerException: NOT_FOUND: io.grpc.StatusRuntimeException: NOT_FOUND: Column not found in table jansUmaPCT: dpop
```

**Comment by yurem** [comment]
In code we have:
```
@ObjectClass(value = "jansUmaPCT")
public class UmaPCT extends AbstractToken {
```

While in schema:
```
objectClasses: ( 1.3.6.1.4.1.48710.1.4.26 NAME 'jansUmaPCT'
  SUP ( top )
```

As result `jansUmaPCT` table has missing attributes defined in `jansUmaPCT`

**Comment by yuriyz** [comment]
Issue is fixed. Closing ticket.
