### ISSUE TITLE
New Interception Script: Token Endpoint

### ISSUE THREAD

**Issue by nynymike** [JanssenProject/jans-auth-server#34]
This would give admins extra flexibility to audit, monitor or extend many flows:
  - extra business logic when a token is refresh (possible adding or removing scopes to the new access token)
  - post client authentication when obtaining an access token (audit logging, monitoring)
  - setting a specific token lifetime based on the context

**Comment by yurem** [comment]
In which flow we will use it? Maybe we can reuse UpdateToken [script](https://github.com/JanssenProject/jans-core/blob/master/script/src/main/java/io/jans/model/custom/script/type/token/UpdateTokenType.java#L10) if it's type conform refresh token script usage. For this we can add more methods to this script type.

**Comment by yuriyz** [comment]
Does it make sense to add support of refresh token as JWT ? In this case we would be able to encode data inside if needed without special handling and still available for both RP and AS. This looks good for access token. 
1. Add refresh token as JWT
2. Add modifyRefreshToken() - invoked when refresh token is jwt.

One more important topic which is raised from time to time is lifetime of the token. There are different conditions how it can/should be tuned dynamically. Thus I guess we need following methods in custom script :

- `getRefreshTokenLiftime(context)` 
- `getIdTokenLiftime(context)`
- `getAccessTokenLiftime(context)`

**Comment by nynymike** [comment]
I like this idea. But it raises a question about the Refresh token signature--how will we get the key that was used to sign the token if key rotation happened? If refresh tokens last 5 days, but key rotation happens every 2 days, the JWKS endpoint would have a new key.  Perhaps we need to add a param to the configuration endpoint to JWKS endpoint that enables developers to retreive old keys? We'd have to open a corresponding issue for this.

**Comment by yuriyz** [comment]
It may break distribution time use case of the keys which we supported for customer because it may lead to 3 and more keys for same algorithm. Also what if refresh token lifetime is more then 5 days (since it's configurable). We can have two approaches:
1) Simple : ask to keep rotation interval bigger then lifetime of token
2) Advanced: save old-expired keys into separate keystore file and publish it on new endpoint or existing endpoint with some additional query parameter. In this case we will not break existing use cases.

**Comment by yuriyz** [comment]
Added `getRefreshTokenLifetimeInSeconds()` method to `UpdateToken` custom script within https://github.com/JanssenProject/jans-auth-server/issues/230

We can keep extending this script.

**Comment by yuriyz** [comment]
Client now has new `updateTokenScriptDns` property in attributes, `UpdateToken` script will be invoked only if it's added to client, e.g. : 
```
"updateTokenScriptDns": ["<update token script dn/key here>"]
```

**Comment by yuriyz** [comment]
All methods described above are supported now, closing ticket as done. Sample script : 
```
class UpdateToken(UpdateTokenType):
    def __init__(self, currentTimeMillis):
        self.currentTimeMillis = currentTimeMillis

    def init(self, customScript, configurationAttributes):
        print "Update token script. Initializing ..."
        print "Update token script. Initialized successfully"

        return True

    def destroy(self, configurationAttributes):
        print "Update token   script. Destroying ..."
        print "Update token    script. Destroyed successfully"
        return True

    def getApiVersion(self):
        return 11

    # Returns boolean, true - indicates that script applied changes
    # This method is called after adding headers and claims. Hence script can override them
    # Note :
    # jsonWebResponse - is JwtHeader, you can use any method to manipulate JWT
    # context is reference of io.jans.oxauth.service.external.context.ExternalUpdateTokenContext (in https://github.com/GluuFederation/oxauth project, )
    def modifyIdToken(self, jsonWebResponse, context):
         return True      

    # Returns boolean, true - indicates that script applied changes. If false is returned token will not be created.
    # refreshToken is reference of io.jans.as.server.model.common.RefreshToken (note authorization grant can be taken as context.getGrant())
    # context is reference of io.jans.as.server.service.external.context.ExternalUpdateTokenContext (in https://github.com/JanssenProject/jans-auth-server project, )
    def modifyRefreshToken(self, refreshToken, context):
        return True

    # Returns boolean, true - indicates that script applied changes. If false is returned token will not be created.
    # accessToken is reference of io.jans.as.server.model.common.AccessToken (note authorization grant can be taken as context.getGrant())
    # context is reference of io.jans.as.server.service.external.context.ExternalUpdateTokenContext (in https://github.com/JanssenProject/jans-auth-server project, )
    def modifyAccessToken(self, accessToken, context):
        return True

    # context is reference of io.jans.as.server.service.external.context.ExternalUpdateTokenContext (in https://github.com/JanssenProject/jans-auth-server project, )
    def getRefreshTokenLifetimeInSeconds(self, context):
        return 0

    # context is reference of io.jans.as.server.service.external.context.ExternalUpdateTokenContext (in https://github.com/JanssenProject/jans-auth-server project, )
    def getIdTokenLifetimeInSeconds(self, context):
        return 0

    # context is reference of io.jans.as.server.service.external.context.ExternalUpdateTokenContext (in https://github.com/JanssenProject/jans-auth-server project, )
    def getAccessTokenLifetimeInSeconds(self, context):
        return 0
```
