### ISSUE TITLE
Ability to restrict available claims from Well-Known OpenID Configuration endpoint

### ISSUE THREAD

**Issue by ruiengana** [JanssenProject/jans-auth-server#37]
In Open Banking scenarios you want to limit claims available in well-known OpenID Configuration endpoint to exclusively required claims.

An example would be something like:
```
{
	"acr_values_supported": ["urn:openbanking:psd2:sca", "urn:openbanking:psd2:ca"],
	"authorization_endpoint": "https://server/auth",
	"claims_parameter_supported": true,
	"claims_supported": ["openbanking_intent_id", "acr", "sub", "sid", "auth_time", "iss"],
	"code_challenge_methods_supported": ["S256"],
	"end_session_endpoint": "https://server/session/end",
	"grant_types_supported": ["implicit", "authorization_code", "refresh_token", "client_credentials"],
	"id_token_signing_alg_values_supported": ["PS256"],
	"issuer": "https://server",
	"jwks_uri": "https://external-server/keystore.jwks",
	"registration_endpoint": "https://server/register",
	"response_modes_supported": ["form_post", "fragment", "query"],
	"response_types_supported": ["code id_token"],
	"scopes_supported": ["openid", "accounts", "payments", "fundsconfirmations", "userinfo", "id_token"],
	"subject_types_supported": ["public"],
	"token_endpoint_auth_methods_supported": ["client_secret_basic", "client_secret_post", "client_secret_jwt", "private_key_jwt", "tls_client_auth"],
	"token_endpoint_auth_signing_alg_values_supported": ["PS256", "ES256"],
	"token_endpoint": "https://server/token",
	"request_object_signing_alg_values_supported": ["PS256", "ES256"],
	"request_parameter_supported": true,
	"request_uri_parameter_supported": false,
	"userinfo_endpoint": "https://server/me",
	"introspection_endpoint": "https://server/token/introspection",
	"introspection_endpoint_auth_methods_supported": ["client_secret_basic", "client_secret_post", "client_secret_jwt", "private_key_jwt", "tls_client_auth"],
	"introspection_endpoint_auth_signing_alg_values_supported": ["PS256", "ES256"],
	"tls_client_certificate_bound_access_tokens": true,
	"claim_types_supported": ["normal"]
}
```

**Comment by nynymike** [comment]
Perhaps we can add a openid-configuration-claims whitelist.

**Comment by yuriyz** [comment]
Visibility will be controlled via additional attribute property `jansVisibileOnDiscovery` (true/false).

**Comment by yuriyz** [comment]
Implemented. If attributes property `jansHideOnDiscovery=false` (default) then claim is visible on discovery page. Otherwise if `jansHideOnDiscovery=true` then claim is not shown.

@shmorri please add it to docs.
@syntrydy FYI in case changes are required on admin UI.

**Comment by ruiengana** [comment]
Brill! Is it available on ConfigAPI and CLI?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by yuriyz** [comment]
@pujavs would you please check it works ok for ConfigAPI ?

**Comment by pujavs** [comment]
@yuriyz, tested jans-config-api  and as well as jans-cli. Changes are working. **However** for jans-cli to work it will have to take the new swagger spec and generate the client. I will inform @mbaser 
**Evidence:**
[Issue#37_Attribute_JansHideOnDiscovery_Test.xlsx](https://github.com/JanssenProject/jans-auth-server/files/6051014/Issue.37_Attribute_JansHideOnDiscovery_Test.xlsx)

**Comment by pujavs** [comment]
jans-cli  spec changes to handle "jansHideOnDiscovery" have been checked in
