### ISSUE TITLE
Revoke Refresh Tokens for Client

### ISSUE THREAD

**Issue by nynymike** [JanssenProject/jans-auth-server#372]
The goal is to revoke all refresh tokens associated with a OIDC client. Perhaps the revocation endpoint could take extra params, like `type=refresh` and `client=11111`? 

Perhaps tokens are an entity worth modeling in SCIM like FIDO tokens? For example, what if an admin wants to list refresh tokens, and then selectively delete some?

**Comment by yuriyz** [comment]
Revoke Endpoint currenly have `client_id` and requires client authentication. `token_type_hint` specifies type of the token (`token_type_hint=access_token` or `token_type_hint=refresh_token`).

Based on this I propose to implement it in following way:
- add configuration property `allowAllValueForRevokeEndpoint: true/false` (false by default). 
   - If true and `token=all&token_type_hint=refresh_token` -> revoke all refresh tokens 
   - If true and `token=all&token_type_hint=access_token` -> revoke all access tokens 
- add support to revoke multiple tokens selectively `token=token1&token=token2&token=token3&token_type_hint=refresh_token`.

In this way we can revoke both refresh and access tokens seletively as well as all of them per client.

**Comment by yuriyz** [comment]
Implemented, closing ticket.
