### ISSUE TITLE
Add support for external JWKS endpoint

### ISSUE THREAD

**Issue by Athloi** [JanssenProject/jans-auth-server#38]
Add support for external JWKS endpoint.

In some trust networks a trusted 3rd party publishes the JWKS - we need a mechanism where the OP doesn't create the key but the OP imports the key and certificate from an external provider.

**Comment by yuriyz** [comment]
@Athloi what is the mechanism of import the key and certificate? Is it some kind of endpoint which has to be called? If yes, where is it described ?

**Comment by yuriyz** [comment]
Workflow looks as :
1. generate CSR manually and send for approval.
2. After approval we get jwks on external endpoint (and kid).
3. Import private key in OP's keystore with provided kid.

**Comment by yuriyz** [comment]
Following is going to be done within this ticket:
1. introduce `externalJwksURI` configuration property. It must point to valid external JWKS. If its set, OP 
2. `jwks_uri` of `.well-known/openid-configuration` must show value of `externalJwksURI` (if its set)
3. private key must be imported in the OPs keystore by `kid` (provided on approval/import)
4. cache content of `externalJwksURI` for configurable amount of time to not hit network each time signature validation is performed (default value 4 hours).

**Comment by yuriyz** [comment]
Implemented in janssen. External jwks has to be set into `jwksUri` configuration property.

**Comment by yuriyz** [comment]
@shmorri please add note to docs.
