### ISSUE TITLE
Use PKCS12 instead of JKS

### ISSUE THREAD

**Issue by martynaslawinska** [JanssenProject/jans-auth-server#61]
_yurem commented on Apr 11, 2019_
JKS is deprecated format. We need to update our code to use PKCS12 instead of JKS

**Comment by smansoft** [comment]
Closed as this Issue has been implemented and merged into the master branch:
https://github.com/JanssenProject/jans-auth-server/pull/382
https://github.com/JanssenProject/jans-auth-server/pull/388
.
