### ISSUE TITLE
Support OpenID Connect Claims Languages

### ISSUE THREAD

**Issue by martynaslawinska** [JanssenProject/jans-auth-server#71]
_nynymike commented on Mar 2, 2017_
Particular Claims MAY be requested by including Claim Names that contain #-separated BCP47 [[RFC5646](https://tools.ietf.org/html/rfc5646)] language tags in the Claims request for example family_name#ja-Kana-JP

http://openid.net/specs/openid-connect-core-1_0.html#IndividualClaimsLanguages

**Comment by ossdhaval** [comment]
Tagging @nynymike as the author of the original oxAuth issue

**Comment by yurem** [comment]
Related to: https://github.com/JanssenProject/jans-auth-server/issues/49

**Comment by nynymike** [comment]
Duplicate https://github.com/JanssenProject/jans-auth-server/issues/49
