### ISSUE TITLE
Whitelist encryption and signing algorithms in JWKS

### ISSUE THREAD

**Issue by nynymike** [JanssenProject/jans-auth-server#74]
Rather then generate all possible signing and encryption algorithms, there should be a property that enables the admin to specify which should be used.

**Comment by yuriyz** [comment]
Limit generated keys and filter out related `*supported` configs according to it.

**Comment by yuriyz** [comment]
Implemented. More details in 4.3 counterpart https://github.com/GluuFederation/oxAuth/issues/1525#issuecomment-801789999

**Comment by yuriyz** [comment]
@shmorri please update docs according to comment https://github.com/GluuFederation/oxAuth/issues/1525#issuecomment-801789999
