### ISSUE TITLE
Feat : Add shared configuration option to disable components

### ISSUE THREAD

**Issue by yurem** [JanssenProject/jans-auth-server#82]
Now there are few options to disable endpoints. We need centralized approach for this. Here is sample how it should looks like:
```
    "enabledComponents":[
        "registration",
        "introspection",
...
    ],
```

For disabled components application should not provide configuration in `.well-known/openid-configuration`

**Comment by yuriyz** [comment]
I like it. Question is to list all components which we want to on/off and group discovery json keys according to component.

**Comment by yuriyz** [comment]
Also for some components we have dedicated boolean fields in global configuration. It has to be consolidated to not produce duplication. For example registration can be turn on/off by `dynamicRegistrationEnabled` boolean property.

**Comment by yurem** [comment]
yep, the main target of this option to consolidate them. And as result it should provide better control of Jans Auth API

**Comment by yuriyz** [comment]
I'm going to start with it to disable services/components which are not allowed for openbanking.

**Comment by yuriyz** [comment]
Currently available components are:
```
"enabledComponents":[
        "health_check",
        "userinfo",
        "clientinfo", 
        "id_generation", 
        "registration", 
        "introspection", 
        "revoke_token", 
        "revoke_session",
        "end_session",
        "status_session",
        "end_session",
        "jans_configuration",
        "ciba",
        "uma",
        "end_session",
        "end_session",
        "end_session",
    STATUS_SESSION("status_session"),
    ],

  
    JANS_CONFIGURATION("jans_configuration"), // /.well-known/jans-configuration
    CIBA("ciba"),
    UMA("uma"),
    U2F("u2f"),
    DEVICE_AUTHZ("device_authz"),
    METRIC("metric"),
    STAT("stat")
```

**Comment by yuriyz** [comment]
Implemented. 
@pujavs is informed to add it to jans-config-api.
@shmorri  would you be so kind to add it to docs.

**Comment by pujavs** [comment]
> Implemented.
> @pujavs is informed to add it to jans-config-api.
> @shmorri would you be so kind to add it to docs.

jans-config-api spec changes checked in related issue https://github.com/JanssenProject/jans-config-api/issues/19
