### ISSUE TITLE
Support features for UK Open Banking DCR

### ISSUE THREAD

**Issue by nynymike** [JanssenProject/jans-auth-server#83]
Holder item for features required to support 
https://openbankinguk.github.io/dcr-docs-pub/v3.3/dynamic-client-registration.html

**Comment by yuriyz** [comment]
DCR is implemented within:
https://github.com/JanssenProject/jans-auth-server/issues/22

Client Credentials Grant for DCR is implemented within:
https://github.com/JanssenProject/jans-auth-server/issues/76

**Comment by yuriyz** [comment]
DCR is implemented. Closing ticket.
